config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


  resources :cars do
    resources :rentals, only: [:new, :create, :show]
  end
  resources :users, only: [:show]
  resources :rentals, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :rentals, dependent: :destroy
  has_one_attached :picture

  CATEGORIES = ['Compact', 'Classic','Minicompact', 'Midsize', 'Large', 'Minivan', 'Small SUV', 'SUV']
  FUELS = ['Gasoline', 'Alcohol', 'Diesel', 'Biodiesel', 'Natural gas', 'Electric', 'Hydrogen', 'Hybrid']

  validates :model, :year, :category, :location, :color, :fuel, :number_of_seats, :price_day, :description, presence: true

  validates :year, numericality: {
    greater_than_or_equal_to: 1900,
    less_than_or_equal_to: -> { Date.current.year }
  }

  validates :description, length: { maximum: 50 }

  validates :price_day, numericality: { greater_than_or_equal_to: 0 }

  validates :number_of_seats, numericality: { only_integer: true, greater_than: 0 }

  geocoded_by :location
  after_validation :geocode, if: ->(obj) { obj.will_save_change_to_location? && (obj.latitude.blank? || obj.longitude.blank?) }

  def unavailable_dates
    rentals.pluck(:pickup_date, :delivered_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :car
  belongs_to :user

  validates :pickup_date, :delivered_date, presence: true
  validate :pickup_date_and_delivered_date_must_be_in_future
  validate :no_overlapping_rentals


  private

  def pickup_date_and_delivered_date_must_be_in_future
    if pickup_date.present? && pickup_date < Date.current
      errors.add(:pickup_date, "must be today or in the future")
    end

    if delivered_date.present? && delivered_date < Date.current
      errors.add(:delivered_date, "must be today or in the future")
    end
  end

  def no_overlapping_rentals
    overlapping_rentals = car.rentals.where.not(id: id).select do |existing_rental|
      (pickup_date < existing_rental.delivered_date && delivered_date > existing_rental.pickup_date)
    end

    if overlapping_rentals.any?
      errors.add(:base, "Try another date for this car!")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cars
  has_many :rentals
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
    # [...]
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      cars_path
    end

    def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :address, :client, :owner])

      # For additional in app/views/devise/registrations/edit.html.erb
      devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :address, :client, :owner])
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def edit
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    @car.picture.attach(params[:car][:picture])
    if @car.save
      redirect_to car_path(@car), notice: 'Car was successfully created.'
    else
      puts @car.errors.full_messages
      flash.now[:alert] = 'There was an error creating the car. Please try again.'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @car = Car.find(params[:id])
    @marker =[{
      lat: @car.latitude,
      lng: @car.longitude

      }]
    @rental = @car.rentals.build
  end

  def update
    @car = Car.find(params[:id])
    @car.picture.attach(params[:car][:picture]) if params[:car][:picture].present?
    if @car.update(car_params)
      redirect_to user_path(current_user), notice: 'Car was successfully updated.'
    else
      flash.now[:alert] = 'There was an error updating the car. Please try again.'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to user_path(current_user), status: :see_other
  end

  private

  def car_params
    params.require(:car).permit(:model, :year, :category, :location, :color, :fuel, :number_of_seats, :description, :picture, :price_day, :rating)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home

  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

  def index
    @rentals = Rental.all
  end

  def new
    @car = Car.find(params[:car_id])
    @rental = Rental.new
    @rental = @car.rentals.build
  end

  def show
    @rental = Rental.find(params[:id])
  end

  def create
    @car = Car.find(params[:car_id])
    @rental = @car.rentals.build(rental_params)
    @rental.user = current_user
    @rental.car = @car

    if @rental.save
      redirect_to user_path(current_user), notice: 'Rental created.'
    else
      flash.now[:alert] = 'Try another date for this car!'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @rental = Rental.find(params[:id])
    @rental.destroy
    redirect_to user_path(current_user), notice: 'Rental deleted.'
  end

  private

  def rental_params
    params.require(:rental).permit(:pickup_date, :delivered_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @cars = @user.cars.includes(:rentals)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_form.html.erb
<%= simple_form_for(car) do |f| %>
  <%= f.input :model, placeholder: "Ex.: Honda, CiberTruck, Mitsubishi..." %>
  <%= f.input :year, placeholder: "Ex.: 1995, 2000...." %>
  <%= f.input :color, placeholder: "Ex.: Black, White, Red, Gray...." %>
  <%= f.input :category, collection: Car::CATEGORIES%>
  <%= f.input :location, placeholder: "Ex.: Street, Number, Neighborhood, City, State"%>
  <%= f.input :fuel, collection: Car::FUELS%>
  <%= f.input :number_of_seats, placeholder: "Insert only numbers" %>
  <%= f.input :price_day, placeholder: "$" %>
  <%= f.input :description, placeholder: "Ex.: leather seats, insuranse...." %>
  <%= f.input :picture %>
  <%= f.submit "Save", class: "btn btn-dark w-100" %>
<% end %>

app/views/cars/edit.html.erb
<div class="bg-black py-2">
  <div class="d-flex mb-3 pt-3">
    <%= link_to user_path(current_user), class: "btn btn-ghost text-white" do %>
      <i class="fa-solid fa-arrow-left fa-2xl" style="color: #ffffff;"></i>
    <% end %>
    <h1 class="mx-3 text-white">Edit your car</h1>
  </div>
</div>

<div class="container mt-5 mb-5">
  <div class="row justify-content-center">
    <div class="col-md-8 col-lg-6">
      <div class="card bg-white shadow-sm p-4">
        <%= render "form", car: @car %>
      </div>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<div class="top">
<header class="bg-black text-white py-4">
    <div class="container text-center">
        <h1>WagonCars</h1>
        <p>Drive the car of your dreams</p>
    </div>
</header>

<div class="container-fluid">
  <div class="row py-3">
    <% @cars.each do |car| %>
      <div class="col-md-4 col-lg-3 mb-4">
        <div class="card bg-white shadow-sm border-0 rounded-4 h-100">
          <%= cl_image_tag car.picture.key, width: 400, height: 200, class: "card-img-top rounded-4 custom-img-index" %>
          <div class="card-body text-center d-flex flex-column">
            <h5 class="card-title mb-2 font-weight-bold">
              <%= link_to car.model, car_path(car), class: "text-dark text-decoration-none" %>
            </h5>
            <p class="card-text mb-1 text-muted">
              <i class="fa-solid fa-dollar-sign"></i> <%= car.price_day %> per day
            </p>
            <p class="card-text mb-1 text-muted">
              <i class="fa-solid fa-person"></i> Seats: <%= car.number_of_seats %>
            </p>
            <p class="card-text text-muted small"><%= car.description %></p>
            <div class="mt-auto">
              <%= link_to "Book it now!", car_path(car), class: "btn btn-dark rounded-5 w-100 py-2 mt-3" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<div class="bg-black py-2">
  <div class="d-flex mb-3 pt-3">
    <%= link_to cars_path, class: "btn btn-ghost text-white" do %>
      <i class="fa-solid fa-arrow-left fa-2xl" style="color: #ffffff;"></i>
    <% end %>
    <h1 class="mx-3 text-white">Add your car to rent!</h1>
  </div>
</div>

<div class="container mt-5 mb-5">
  <div class="row justify-content-center">
    <div class="col-md-8 col-lg-6">
      <div class="card bg-white shadow-sm p-4">
        <%= render "form", car: @car %>
      </div>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="bg-black py-4">
  <div class="d-flex align-items-center justify-content-between">
    <%= link_to cars_path, class: "btn btn-ghost text-white d-flex align-items-center" do %>
      <i class="fa-solid fa-arrow-left fa-2xl" style="color: #ffffff;"></i>
    <% end %>
    <h1 class="mx-3 text-white text-center flex-grow-1"><%= @car.model %></h1>
    <div class="btn btn-ghost text-white invisible">
      <i class="fa-solid fa-arrow-left fa-2xl"></i>
    </div>
  </div>
</div>

<div class="container">

  <div class="row mt-3">
    <div class="col-md-8">
      <% if @car.picture.attached? %>
        <div class="card bg-white rounded-4 shadow-sm">
          <%= cl_image_tag @car.picture.key, class: "img-fluid w-100 rounded-4", style: "max-height: 435px; object-fit: cover;" %>
        </div>
      <% end %>
    </div>

    <div class="col-md-4">
      <div class="card bg-white rounded-4 shadow-sm">
        <div class="card-body">
          <h3 class="text-center"><strong>Details</strong></h3>
          <p><i class="fa-solid fa-car-side"></i> <%= @car.model %></p>
          <p><i class="fa-regular fa-calendar-days"></i> <%= @car.year %></p>
          <p><i class="fa-solid fa-palette"></i> <%= @car.color %></p>
          <p><i class="fa-solid fa-layer-group"></i> <%= @car.category %></p>
          <p><i class="fa-solid fa-person"></i> <%= @car.number_of_seats %> seats </p>
          <p><i class="fa-solid fa-gas-pump"></i> <%= @car.fuel %></p>
          <p><i class="fa-solid fa-user"></i> <%= @car.user.user_name %></p>
          <p><i class="fa-solid fa-location-dot"></i> <%= @car.location %></p>
          <p><i class="fa-solid fa-file-lines"></i> <%= @car.description %></p>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-8 text-center">
      <div class="card mb-3 rounded-5">
        <div style="width: 100%; height: 600px;"
          data-controller="map"
          data-map-markers-value="<%= @marker.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card bg-white rounded-4 shadow-sm p-4" data-controller="calculator">
        <h3 class="text-center"><strong>Create a Reservation</strong></h3>
        <h5 class="mb-2 text-center"><strong>$ / day: <span data-calculator-target="pricePerDay"><%= @car.price_day %></strong></span></h5>
        <%= simple_form_for([@car, @rental], data: { unavailable_dates: @car.unavailable_dates.to_json }) do |f| %>

          <div class="mb-3">
            <%= f.input :pickup_date, as: :string, label: "Pickup Date", input_html: { class: "form-control", data: { calculator_target: 'startDate', controller: "datepicker", action: "change->calculator#updateTotalPrice" } } %>
          </div>

          <div class="mb-3">
            <%= f.input :delivered_date, as: :string, label: "Delivered Date", input_html: { class: "form-control", data: { calculator_target: 'endDate', controller: "datepicker", action: "change->calculator#updateTotalPrice" } } %>
          </div>

          <p class="mb-4">Total price: <span data-calculator-target="totalprice">0</span></p>

          <%= f.submit "Create a rental", class:"btn btn-dark w-100" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WagonCars</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-beige">
    <div class='d-flex flex-column min-vh-100'>
      <%= render "shared/flashes" %>
      <%= render "shared/user_dropdown" %>
      <article class="flex-grow-1">
      <%= yield %>
      </article>

      <footer class="bg-dark text-white py-2">
        <div class="container text-center">
            <p class="small">&copy; 2024 WagonCars. All rights reserved.</p>
        </div>
      </footer>

    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="bg-beige">
  <% unless user_signed_in? %>
    <div class="position-absolute top-0 end-0 m-3" style="z-index: 1050;">
      <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-primary rounded-5 px-4' %>
    </div>
  <% end %>
  <header class="bg-dark text-white py-3">
      <div class="container text-center">
          <h1 class="h3 mb-2">WagonCars</h1>
          <p class="small mb-0">Your trusted platform for car rentals.</p>
      </div>
  </header>

  <div class="container my-4">
      <div class="row justify-content-center">
          <div class="col-md-5 col-lg-4 mb-4">
              <div class="p-3 shadow-sm rounded-5 border bg-white">
                  <h2 class="h5 mb-3 text-center">For Car Owners</h2>
                  <img src="https://img.freepik.com/free-vector/by-my-car-illustration-concept_114360-831.jpg"
                    alt="Car Owner" class="img-fluid mb-3">
                  <p class="small text-center">List your car on WagonCars and start earning. It’s simple and secure to share your car with trusted users.</p>
                  <div class="d-flex justify-content-center">
                    <%= link_to 'Put your car to rent!', new_user_session_path, class: "btn btn-primary rounded-5" %>
                  </div>
              </div>
          </div>

          <div class="col-md-5 col-lg-4 mb-4">
              <div class="p-3 shadow-sm rounded-5 border bg-white">
                  <h2 class="h5 mb-3 text-center">For Renters</h2>
                  <img src="https://png.pngtree.com/png-clipart/20200701/original/pngtree-searching-buy-and-rent-car-flat-illustration-png-image_5426813.jpg"
                    alt="Car Renter" class="img-fluid mb-3">
                  <p class="small text-center">Looking for a car to rent? Find a variety of vehicles that suit your needs and budget, all in one place.</p>
                  <div class="d-flex justify-content-center">
                    <%= link_to 'Rent a car now!', new_user_session_path, class: "btn btn-primary rounded-5" %>
                  </div>
              </div>
          </div>
      </div>


  </div>
</div>

app/views/rentals/edit.html.erb
<h1>Edit the Rental</h1>

<%= simple_form_for(@rental) do |f| %>
  <%= f.input :model %>
  <%= f.input :year %>
  <%= f.input :category %>
  <%= f.input :location %>

  <%= f.submit %>
<% end %>

app/views/rentals/index.html.erb
<h1>My reservations</h1>

<% @rentals.each do |rental| %>
  <div class="card">
    <div>
      Pick up date : <%= rental.pickup_date %>
    </div>
    <div>
      Delivered date : <%= rental.delivered_date %>
    </div>
  </div>
<% end %>

<%= link_to "Back", cars_path %>

app/views/rentals/new.html.erb
<div class="bg-dark text-white py-2">
  <div class="d-flex mb-3 pt-3">
  <%= link_to cars_path, class: "btn btn-ghost text-white" do %>
    <i class="fa-solid fa-arrow-left fa-2xl" style="color: #ffffff;"></i>
  <% end %>
  <h1 class="mx-3 text-white">Create a Reservation</h1>
  </div>
</div>

<div class="container mt-5 d-flex justify-content-center">
  <div class="card bg-white shadow-sm p-4" data-controller="calculator">
    <%= simple_form_for([@car, @rental], data: { unavailable_dates: @car.unavailable_dates.to_json }) do |f| %>

      <div class="mb-3">
        <%= f.input :pickup_date, as: :string, label: "Pickup Date", input_html: { class: "form-control", data: { calculator_target: 'startDate', controller: "datepicker", action: "change->calculator#updateTotalPrice" } } %>
      </div>

      <div class="mb-3">
        <%= f.input :delivered_date, as: :string, label: "Delivered Date", input_html: { class: "form-control", data: { calculator_target: 'endDate', controller: "datepicker", action: "change->calculator#updateTotalPrice" } } %>
      </div>

      <p class="mb-2">Price per day: <span data-calculator-target="pricePerDay"><%= @car.price_day %></span></p>
      <p class="mb-4">Total price: <span data-calculator-target="totalprice">0</span></p>

      <%= f.submit "Create a rental", class:"btn btn-dark w-100" %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to cars_path, class: "navbar-brand" do %>
      <%= image_tag "default_car.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="m-2">
            <strong>Hello, <%= current_user.user_name %>!</strong>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{current_user.user_name}", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end bg-white" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", user_path(current_user), class: 'btn btn-ghost' %>
              <%= link_to 'Add New Car', new_car_path, class: 'btn btn-ghost' %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_user_dropdown.html.erb
<% if user_signed_in? %>
  <div class="position-absolute top-0 end-0 m-3" style="z-index: 1050;">
    <div class="dropdown">
      <a href="#" class="d-inline-block" id="userDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background: none; border: none;">
        <i class="fa fa-bars fa-2x" style="color: white;"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-end bg-white" aria-labelledby="userDropdown">
        <span class="dropdown-item-text"><strong><%= current_user.user_name.presence || current_user.email %></strong></span>
        <div class="dropdown-divider"></div>
        <%= link_to "My profile", user_path(current_user), class: 'dropdown-item' %>
        <%= link_to 'Add New Car', new_car_path, class: 'dropdown-item' %>
        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="bg-black">


  <div class="d-flex mb-3 pt-3">
    <%= link_to cars_path, class: "btn btn-ghost text-white" do %>
      <i class="fa-solid fa-arrow-left fa-2xl" style="color: #ffffff;"></i>
    <% end %>


    <h1 class="mx-3 text-white">My profile</h1>
  </div>


  <div class="mx-3 pb-3 text-white">
    Email : <%= current_user.email %>
  </div>
</div>

<div class="container-fluid">
  <div class="row justify-content-evenly mt-3 ">
    <div class="col-5">
      <div class="card bg-white rounded-5">
        <div class="m-3 p-3">
          <h2 class="mb-3 pb-3">My Reservations</h2>
          <% if current_user.rentals.any? %>
            <% current_user.rentals.each do |rental| %>
              <div class="card mb-3 px-3 pt-3">
                <div class="row">
                  <div class="col-4 d-flex align-items-center">
                    <%= cl_image_tag rental.car.picture.key, class: "card-img-top border custom-img" %>
                  </div>
                  <div class="col-8">
                    <div class="mb-3">
                      <strong><%= rental.car.model %></strong>
                    </div>
                    <div class="d-flex justify-content-between align-items-center mb-3">
                      <div>
                        <p>Pick up date: <%= rental.pickup_date %></p>
                        <p>Return date: <%= rental.delivered_date %></p>
                      </div>
                      <div>
                        <%= link_to "Cancel",
                        rental_path(rental),
                        data: { turbo_method: :delete, turbo_confirm: "No refund!" },
                        class: "btn border-danger rounded-5 hover-effect-red"
                        %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <p><small>You do not have any car booked currently.</small></p>
          <% end %>
        </div>
      </div>
    </div>

  <div class="col-5">
    <div class="card bg-white rounded-5">
      <div class="m-3 p-3">
        <h2 class="mb-3 pb-3">My Cars Rented</h2>
      </div>
      <div class="mx-3 px-3">
        <% total_rentals = current_user.cars.sum { |car| car.rentals.size } %>
        <% if current_user.cars.empty? || total_rentals == 0 %>
          <p><small>You do not have any car rented currently.</small></p>
        <% else %>
          <% current_user.cars.each do |car|%>
            <div class="card mb-3 p-3">
              <div>
                <p><strong><%= car.model %></strong></p>
              </div>
              <% if car.rentals.any? %>
                <% car.rentals.each do |rental| %>
                  <div class="card p-3 mb-3 bg-white">
                    <li>
                      Pick-up date : <%= rental.pickup_date %>,
                      Return date : <%= rental.delivered_date %>
                      <div class="mb-1s mt-2"><strong>Rented by :</strong> <%= rental.user.email %></div>
                    </li>
                  </div>
                <% end %>
              <% else %>
                <p><small>No current rental for this car.</small></p>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
  <h2 class="mt-5 mx-3 pt-3 text-center"><strong>My Cars</strong></h2>
  <div class="row p-3">
    <% current_user.cars.each do |car|%>
      <div class="col-6 mb-3">
        <div class="card bg-white ">
          <div class="row m-3">
            <div class="col-6">
              <div class="card shadow-sm">
                <div class="card-body">
                  <h4 class="text-center mb-2"><strong>Car informations :</strong></h4>
                  <p><i class="fa-solid fa-car-side"></i> <%= car.model %></p>
                  <p><i class="fa-regular fa-calendar-days"></i> <%= car.year %></p>
                  <p><i class="fa-solid fa-palette"></i> <%= car.color %></p>
                  <p><i class="fa-solid fa-layer-group"></i> <%= car.category %></p>
                  <p><i class="fa-solid fa-location-dot"></i> <%= car.location %></p>
                  <p><i class="fa-solid fa-gas-pump"></i> <%= car.fuel %></p>
                  <p><i class="fa-solid fa-person"></i> <%= car.number_of_seats %> seats </p>
                </div>
              </div>
            </div>

            <div class="d-flex flex-column col-6">
              <%= cl_image_tag car.picture.key, width: 300, height: 160, class: "card-img-top border custom-img" %>
              <p class="my-4"><strong>Description of your car : </strong><%= car.description %></p>
              <div class=" d-flex flex-column mt-auto">
                <%= link_to 'Edit your car', edit_car_path(car), class: "btn border-warning mb-2 text-color-warning hover-effect-orange rounded-5" %>
                <%= link_to "Remove from our website",
                car_path(car),
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                class: "btn border-danger hover-effect-red rounded-5"
                %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>